### ISSUE TITLE
你好，对于这块整合我一知半解、很希望你的教程能继续更新、

### ISSUE THREAD

**Issue by FatherGodHz** [Donng/laravel-vue-iview#1]
你好，对于这块整合我一知半解、很希望你的教程能继续更新、
看你的 commit 文件可能量有点大、很难一次性消化掉、

**Comment by donng** [comment]
如果对vue前端的构成有问题，可以阅读 [https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/README](vue前端项目)。
整合可以大致说一下什么情况，我不太了解具体是哪方面。

**Comment by FatherGodHz** [comment]
非常感谢回复、我先参考这个了解一下、到时候有疑问的地方还望指教

**Comment by FatherGodHz** [comment]
@Donng  不好意思 忘记关闭了
