### ISSUE TITLE
你好,最近自己也再学习,看到楼主这个真的很受用

### ISSUE THREAD

**Issue by pefecter** [Donng/laravel-vue-iview#2]
希望能继续更新更多一点的基础功能吧
反馈一下,标签点击×并没有关闭了,我只用过element  还没怎么看iview,不知道是Bug还是楼主做了什么??
谢谢,会继续学习,已star

**Comment by donng** [comment]
@pefecter 最近在做 Go 语言方面的东西，Bug 的话我会及时处理，基础功能就没那么快了

**Comment by pefecter** [comment]
好的,谢谢楼主啊,因为我也刚开始用laravel,所以还是很多不明白,就只好一点点学习着这个项目,主要可能还是搭建的时候遇到问题比较多(基础搭建能行,卡权限这些部分,学习中!),希望楼主能有时间更新项目,会继续关注~
