### ISSUE TITLE
发现两个小问题

### ISSUE THREAD

**Issue by leslieeilsel** [Donng/laravel-vue-iview#4]
很感谢分享这么棒的项目，对于新手的我来说真的很有帮助。
在使用了两天之后，发现了几个问题。
- 关闭标签页之后，页面内容依然显示
- 关闭标签页之后，其对应的菜单依然高亮，且无法点击打开标签页

如下图：
![avatar](http://m.qpic.cn/psb?/V12ol6gx2nrILn/8tqpLFyBdRFoMt1LhWRRHH8AXBkOFlxHhJm1SeMt.Rs!/b/dFIBAAAAAAAA&bo=TQXfAk0F3wICOR0!&rf=viewer_4)

**Comment by donng** [comment]
@leslieeilsel 周末修复，如有兴趣也欢迎 pr

**Comment by donng** [comment]
@leslieeilsel 此 bug 已处理

**Comment by leslieeilsel** [comment]
@Donng 好的，非常感谢。
另外有个问题，为什么在github的commit历史中没有看到这两条更新。
![avatar](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/V*Y4f0xnmuNZbUesx89woQi3MJbPlyWVFJDrnzGg5uQ!/r/dFMBAAAAAAAA)

**Comment by donng** [comment]
@leslieeilsel  后面考虑到盲目追新意义不大，所以回退到长期支持版本了

**Comment by leslieeilsel** [comment]
@Donng 也是，我是比较喜欢新的东西。
看了下标签页页的修改，感觉标签页的交互还是不够好。感觉iview-admin的标签栏更符合习惯。
- 关闭标签页后返回首页有点暴力
- 在标签页之间切换时，如果标签对应的菜单是折叠的，应该展开并高亮。未选中的就折叠起来

所以，要不要集成iview-admin进来（调皮！哈哈！）

**Comment by donng** [comment]
@leslieeilsel 可以参考 iview-admin 做类似 tags 的细节优化，集成应该没必要，80% 的内容还是页面插件。而且集成进来要跟进 iview-admin 的更新不太实现。
工作中的项目更推荐 vue + lumen 搭配。这个也就学习一下 Laravel vue 集成思路，当然做个内部小后台也问题不大。
